import type { ControlSection, PointStatus } from "@/lab/types";
import { CoilCurve } from "./CoilCurve";
import type { CoilInputs, CoilOutputs } from "./model";

type I = CoilInputs;
type O = CoilOutputs;

const cooling = (i: I) => i.mode === "cooling";
const heating = (i: I) => i.mode === "heating";
const datStatus = (o: O): PointStatus => (o.datDisplayed < 40 ? "alarm" : "ok");

export const controls: ControlSection<I, O>[] = [
  // ── bench ─────────────────────────────────────────────────────────────────────
  {
    id: "curve",
    title: "Water ≠ heat",
    description: "How much of the coil's water is flowing, against how much heating or cooling that buys.",
    slot: "bench",
    controls: [
      {
        kind: "custom",
        id: "coil-curve",
        label: "Coil and valve curves",
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        Component: CoilCurve as any,
      },
    ],
  },
  {
    id: "points",
    title: "Readings",
    description: "What the control system reads, next to what's really happening.",
    slot: "bench",
    controls: [
      {
        kind: "readout",
        id: "dat",
        point: "AHU-1/DA-T",
        label: "Discharge air temperature",
        unit: "°F",
        digits: 1,
        value: (o) => o.datDisplayed,
        status: datStatus,
      },
      {
        kind: "readout",
        id: "cmd",
        point: "AHU-1/VLV-CMD",
        label: "Valve command (active coil)",
        unit: "%",
        value: (o) => o.cmd,
        status: (o) => (o.manual ? "overridden" : "ok"),
        pair: { label: "FB", value: (o) => o.actuatorPct },
      },
      {
        kind: "readout",
        id: "loop",
        point: "AHU-1/DAT-LOOP",
        label: "What the program wants (P16)",
        unit: "%",
        value: (o) => o.loopOut,
      },
      {
        kind: "readout",
        id: "flow",
        point: "water",
        label: "Water flowing, of the valve's full flow",
        unit: "%",
        reality: true,
        value: (o) => o.flowOfMax,
      },
      {
        kind: "readout",
        id: "heat",
        point: "heat moved",
        label: "Heating or cooling, of what the coil can do",
        unit: "%",
        reality: true,
        value: (o) => Math.max(0, o.capOfMax),
      },
      {
        kind: "readout",
        id: "dtw",
        point: "water ΔT",
        label: "How much the water warms or cools",
        unit: "°F",
        digits: 1,
        reality: true,
        value: (o) => o.activeDt,
      },
      {
        kind: "readout",
        id: "fight",
        point: "shut coil",
        label: "What the shut coil does to the air anyway",
        unit: "°F",
        digits: 1,
        reality: true,
        value: (o) => (o.cooling ? Math.max(0, o.hwRise) : Math.max(0, o.chwDrop)),
      },
    ],
  },
  {
    id: "trend",
    title: "Trend",
    description: "The last 90 seconds of discharge air against its target.",
    slot: "bench",
    controls: [
      {
        kind: "trend",
        id: "dat-trend",
        label: "Discharge air loop",
        window: 90,
        pens: [
          { id: "dat", label: "Discharge", unit: "°", axis: "temp", color: "#f3eee4", value: (o) => o.datDisplayed },
          { id: "sp", label: "Target", unit: "°", axis: "temp", color: "#7f7c75", dashed: true, value: (o) => o.sp },
          { id: "vlv", label: "Valve", unit: "%", axis: "pct", color: "#ff5a1f", value: (o) => o.cmd },
          { id: "heat", label: "Heat moved", unit: "%", axis: "pct", color: "#27b7ff", dashed: true, value: (o) => Math.max(0, o.capOfMax) },
        ],
      },
    ],
  },

  // ── side rack ─────────────────────────────────────────────────────────────────
  {
    id: "coil",
    title: "Coil",
    description: "Which coil the loop drives: cooling with chilled water, or heating with hot water. The other valve is held shut.",
    slot: "side",
    controls: [
      {
        kind: "segmented",
        id: "mode",
        label: "Active coil",
        options: [
          { value: "cooling", label: "Cooling" },
          { value: "heating", label: "Heating" },
        ],
        get: (i) => i.mode,
        set: (i, v) => ({ ...i, mode: v as I["mode"], override: { ...i.override, mode: "auto" } }),
      },
    ],
  },
  {
    id: "conditions",
    title: "Conditions",
    description: "The air arriving at the coils, and the water the plant is sending.",
    slot: "side",
    controls: [
      {
        kind: "slider",
        id: "eat",
        label: "Entering air",
        unit: "°F",
        min: 30,
        max: 95,
        step: 1,
        get: (i) => i.eat,
        set: (i, v) => ({ ...i, eat: v }),
        marks: (i) => [{ label: "TARGET", value: i.mode === "cooling" ? i.coolSp : i.heatSp }],
      },
      {
        kind: "slider",
        id: "rh",
        label: "Entering humidity",
        unit: "%",
        min: 20,
        max: 90,
        step: 1,
        hint: "Humid air condenses on a cold coil. That water drips into the drain pan.",
        when: (i: I) => cooling(i),
        get: (i) => i.rh,
        set: (i, v) => ({ ...i, rh: v }),
      },
      {
        kind: "slider",
        id: "chw",
        label: "Chilled water from the plant",
        unit: "°F",
        min: 38,
        max: 58,
        step: 0.5,
        when: (i: I) => cooling(i),
        get: (i) => i.chwEwt,
        set: (i, v) => ({ ...i, chwEwt: v }),
      },
      {
        kind: "slider",
        id: "hw",
        label: "Hot water from the plant",
        unit: "°F",
        min: 100,
        max: 190,
        step: 1,
        when: (i: I) => heating(i),
        get: (i) => i.hwEwt,
        set: (i, v) => ({ ...i, hwEwt: v }),
      },
      {
        kind: "slider",
        id: "airflow",
        label: "Airflow",
        unit: "%",
        min: 50,
        max: 110,
        step: 1,
        get: (i) => i.airflow,
        set: (i, v) => ({ ...i, airflow: v }),
      },
    ],
  },
  {
    id: "setpoints",
    title: "Setpoints",
    description: "The temperature the air should leave at.",
    slot: "side",
    controls: [
      {
        kind: "setpoint",
        id: "cool-sp",
        label: "Discharge air target",
        point: "DA-T-SP · cooling",
        unit: "°F",
        min: 48,
        max: 65,
        step: 0.5,
        digits: 1,
        when: (i: I) => cooling(i),
        get: (i) => i.coolSp,
        set: (i, v) => ({ ...i, coolSp: v }),
      },
      {
        kind: "setpoint",
        id: "heat-sp",
        label: "Discharge air target",
        point: "DA-T-SP · heating",
        unit: "°F",
        min: 55,
        max: 95,
        step: 0.5,
        digits: 1,
        when: (i: I) => heating(i),
        get: (i) => i.heatSp,
        set: (i, v) => ({ ...i, heatSp: v }),
      },
    ],
  },
  {
    id: "control",
    title: "Control",
    description: "Who's driving the valve, and how hard the loop reacts.",
    slot: "side",
    controls: [
      {
        kind: "override",
        id: "override",
        label: "Valve on the active coil",
        point: "AHU-1/VLV-CMD",
        unit: "%",
        min: 0,
        max: 100,
        step: 1,
        get: (i) => i.override,
        set: (i, v) => ({ ...i, override: v }),
        programValue: (o) => o.loopOut,
        programPriority: 16,
        activePriority: (o) => o.activePriority,
      },
      {
        kind: "knob",
        id: "kp",
        label: "Gain",
        unit: "%/°F",
        min: 0.5,
        max: 15,
        step: 0.5,
        digits: 1,
        color: "orange",
        warnAbove: 8,
        hint: "How hard the loop reacts to being off target (proportional gain).",
        get: (i) => i.kp,
        set: (i, v) => ({ ...i, kp: v }),
      },
      {
        kind: "knob",
        id: "ti",
        label: "Reset time",
        unit: "s",
        min: 3,
        max: 60,
        step: 1,
        digits: 0,
        color: "white",
        hint: "How patiently the loop works off a steady error (integral time).",
        get: (i) => i.ti,
        set: (i, v) => ({ ...i, ti: v }),
      },
    ],
  },
  {
    id: "service",
    title: "Service",
    description: "Break things on purpose.",
    slot: "side",
    controls: [
      {
        kind: "faults",
        id: "faults",
        label: "Fault injector",
        active: (i) => (i.faults.hwLeak > 0 ? 1 : 0) + (i.faults.chwLeak > 0 ? 1 : 0) + (i.faults.stuck ? 1 : 0) + (i.faults.datOffset !== 0 ? 1 : 0),
        items: [
          {
            kind: "slider",
            id: "hw-leak",
            label: "Heating valve leaks",
            hint: "Water gets past the closed heating valve. The coil warms the air even though the valve reads 0 %.",
            unit: "%",
            min: 0,
            max: 20,
            step: 1,
            get: (i) => Math.round(i.faults.hwLeak * 100),
            set: (i, v) => ({ ...i, faults: { ...i.faults, hwLeak: v / 100 } }),
          },
          {
            kind: "slider",
            id: "chw-leak",
            label: "Cooling valve leaks",
            hint: "Chilled water gets past the closed cooling valve and cools air that's being heated.",
            unit: "%",
            min: 0,
            max: 20,
            step: 1,
            get: (i) => Math.round(i.faults.chwLeak * 100),
            set: (i, v) => ({ ...i, faults: { ...i.faults, chwLeak: v / 100 } }),
          },
          {
            kind: "toggle",
            id: "stuck",
            label: "Stuck valve stem",
            hint: "The actuator keeps moving and reporting, but the stem on the active valve stays put.",
            capture: "stemPct",
            get: (i) => i.faults.stuck,
            set: (i, on, capture) => ({ ...i, faults: { ...i.faults, stuck: on, stuckAt: on ? Math.round(capture) : i.faults.stuckAt } }),
          },
          {
            kind: "slider",
            id: "dat-offset",
            label: "Discharge sensor error",
            hint: "The sensor reads high or low. The loop faithfully controls to the wrong number.",
            unit: "°F",
            min: -6,
            max: 6,
            step: 0.5,
            get: (i) => i.faults.datOffset,
            set: (i, v) => ({ ...i, faults: { ...i.faults, datOffset: v } }),
          },
        ],
      },
    ],
  },
];
