import type { ControlSection, PointStatus } from "@/lab/types";
import { CurvePlot } from "./CurvePlot";
import type { EconInputs, EconOutputs } from "./model";

type I = EconInputs;
type O = EconOutputs;

const matStatus = (o: O): PointStatus => (o.matDisplayed < 40 ? "alarm" : "ok");

export const controls: ControlSection<I, O>[] = [
  // ── bench: the instrument row under the display ─────────────────────────────
  {
    id: "curve",
    title: "Position ≠ percentage",
    description: "How far the damper is open, against how much of the air is actually from outside.",
    slot: "bench",
    controls: [
      {
        kind: "custom",
        id: "installed-curve",
        label: "Installed characteristic",
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        Component: CurvePlot as any,
      },
    ],
  },
  {
    id: "points",
    title: "Readings",
    description: "What the control system reads, next to what's really happening.",
    slot: "bench",
    controls: [
      {
        kind: "readout",
        id: "mat",
        point: "AHU-1/MA-T",
        label: "Mixed-air temperature",
        unit: "°F",
        digits: 1,
        value: (o) => o.matDisplayed,
        status: matStatus,
      },
      {
        kind: "readout",
        id: "cmd",
        point: "AHU-1/OAD-CMD",
        label: "Damper command",
        unit: "%",
        value: (o) => o.cmd,
        status: (o) => (o.freezeStage ? "alarm" : o.manual ? "overridden" : "ok"),
        pair: { label: "FB", value: (o) => o.actuatorPosPct },
      },
      {
        kind: "readout",
        id: "loop",
        point: "AHU-1/MAT-LOOP",
        label: "What the program wants (P16)",
        unit: "%",
        value: (o) => o.loopOut,
      },
      {
        kind: "readout",
        id: "oa-calc",
        point: "AHU-1/OA-PCT",
        label: "Outside air %, estimated from temperatures",
        unit: "%",
        value: (o) => o.oaPctCalc,
      },
      {
        kind: "readout",
        id: "blade",
        point: "blades",
        label: "Where the blades really are",
        unit: "%",
        reality: true,
        value: (o) => o.bladePosPct,
      },
      {
        kind: "readout",
        id: "oa-true",
        point: "outside air",
        label: "Share of the air that's really from outside",
        unit: "%",
        reality: true,
        value: (o) => o.oaPct,
      },
      {
        kind: "readout",
        id: "mat-true",
        point: "mixed air",
        label: "Real mixed-air temperature",
        unit: "°F",
        digits: 1,
        reality: true,
        value: (o) => o.matTrue,
      },
    ],
  },
  {
    id: "trend",
    title: "Trend",
    description: "The last 90 seconds of mixed-air temperature against its target.",
    slot: "bench",
    controls: [
      {
        kind: "trend",
        id: "mat-trend",
        label: "MAT loop",
        window: 90,
        pens: [
          { id: "mat", label: "Mixed", unit: "°", axis: "temp", color: "#f3eee4", value: (o) => o.matDisplayed },
          { id: "sp", label: "Target", unit: "°", axis: "temp", color: "#7f7c75", dashed: true, value: (o) => o.matSp },
          { id: "cmd", label: "Damper", unit: "%", axis: "pct", color: "#ff5a1f", value: (o) => o.cmd },
          { id: "oa", label: "Outside air", unit: "%", axis: "pct", color: "#27b7ff", dashed: true, value: (o) => o.oaPct },
        ],
      },
    ],
  },

  // ── side rack ───────────────────────────────────────────────────────────────
  {
    id: "weather",
    title: "Conditions",
    description: "The weather outside, and the air coming back from the rooms.",
    slot: "side",
    controls: [
      {
        kind: "slider",
        id: "oat",
        label: "Outside air",
        unit: "°F",
        min: -10,
        max: 110,
        step: 1,
        hint: "Simulated weather. Free cooling runs below the high limit.",
        get: (i) => i.oat,
        set: (i, v) => ({ ...i, oat: v }),
        marks: (i) => [
          { label: "TARGET", value: i.matSp },
          { label: "LIMIT", value: i.highLimit },
        ],
      },
      {
        kind: "slider",
        id: "rat",
        label: "Return air (from the rooms)",
        unit: "°F",
        min: 62,
        max: 82,
        step: 0.5,
        get: (i) => i.rat,
        set: (i, v) => ({ ...i, rat: v }),
      },
    ],
  },
  {
    id: "setpoints",
    title: "Setpoints",
    description: "Targets and limits the control system works to.",
    slot: "side",
    controls: [
      {
        kind: "setpoint",
        id: "mat-sp",
        label: "Mixed-air target",
        point: "MA-T-SP",
        unit: "°F",
        min: 45,
        max: 65,
        step: 0.5,
        digits: 1,
        get: (i) => i.matSp,
        set: (i, v) => ({ ...i, matSp: v }),
      },
      {
        kind: "setpoint",
        id: "min-oa",
        label: "Minimum damper position",
        point: "OAD-MIN",
        unit: "%",
        min: 0,
        max: 60,
        step: 1,
        get: (i) => i.minOaPos,
        set: (i, v) => ({ ...i, minOaPos: v }),
      },
      {
        kind: "setpoint",
        id: "high-limit",
        label: "Free cooling up to",
        point: "ECON-HL · high limit",
        unit: "°F",
        min: 50,
        max: 85,
        step: 1,
        get: (i) => i.highLimit,
        set: (i, v) => ({ ...i, highLimit: v }),
      },
    ],
  },
  {
    id: "command",
    title: "Control",
    description: "Who's driving the damper, and how hard the loop reacts.",
    slot: "side",
    controls: [
      {
        kind: "override",
        id: "override",
        label: "Outside-air damper",
        point: "AHU-1/OAD-CMD",
        unit: "%",
        min: 0,
        max: 100,
        step: 1,
        get: (i) => i.override,
        set: (i, v) => ({ ...i, override: v }),
        programValue: (o) => o.loopOut,
        programPriority: 16,
        activePriority: (o) => o.activePriority,
        otherSlots: (o) => ({ 5: Number.isFinite(o.p5) ? o.p5 : null }),
      },
      {
        kind: "knob",
        id: "kp",
        label: "Gain",
        unit: "%/°F",
        min: 0.5,
        max: 25,
        step: 0.5,
        digits: 1,
        color: "orange",
        warnAbove: 10,
        hint: "How hard the loop reacts to being off target (proportional gain). Turn it past the amber zone and the damper hunts back and forth.",
        get: (i) => i.kp,
        set: (i, v) => ({ ...i, kp: v }),
      },
      {
        kind: "knob",
        id: "ti",
        label: "Reset time",
        unit: "s",
        hint: "How patiently the loop works off a steady error (integral time). Shorter is more aggressive.",
        min: 3,
        max: 60,
        step: 1,
        digits: 0,
        color: "white",
        get: (i) => i.ti,
        set: (i, v) => ({ ...i, ti: v }),
      },
    ],
  },
  {
    id: "service",
    title: "Service",
    description: "Break things on purpose.",
    slot: "side",
    controls: [
      {
        kind: "faults",
        id: "faults",
        label: "Fault injector",
        active: (i) => (i.faults.stuckDamper ? 1 : 0) + (i.faults.matOffset !== 0 ? 1 : 0),
        items: [
          {
            kind: "toggle",
            id: "stuck",
            label: "Slipped linkage",
            hint: "The motor keeps turning and reporting, but it's no longer connected to the blades, so they stay put.",
            capture: "bladePosPct",
            get: (i) => i.faults.stuckDamper,
            set: (i, on, capture) => ({ ...i, faults: { ...i.faults, stuckDamper: on, stuckAt: on ? Math.round(capture) : i.faults.stuckAt } }),
          },
          {
            kind: "slider",
            id: "offset",
            label: "Mixed-air sensor error",
            hint: "The sensor reads high or low. The loop faithfully controls to the wrong number.",
            unit: "°F",
            min: -8,
            max: 8,
            step: 0.5,
            get: (i) => i.faults.matOffset,
            set: (i, v) => ({ ...i, faults: { ...i.faults, matOffset: v } }),
          },
        ],
      },
    ],
  },
];
