import type { ControlSection, PointStatus } from "@/lab/types";
import { BoxCurves } from "./BoxCurves";
import type { VavInputs, VavOutputs } from "./model";

type I = VavInputs;
type O = VavOutputs;

const zoneStatus = (o: O): PointStatus => (o.zoneDisplayed > o.zoneSp + 3 ? "alarm" : "ok");

export const controls: ControlSection<I, O>[] = [
  // ── bench ─────────────────────────────────────────────────────────────────────
  {
    id: "curves",
    title: "Airflow ≠ damper position",
    description: "What the damper can deliver at the duct pressure it's getting, and how far the airflow reading can be trusted.",
    slot: "bench",
    controls: [
      {
        kind: "custom",
        id: "box-curves",
        label: "Damper and flow-sensor curves",
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        Component: BoxCurves as any,
      },
    ],
  },
  {
    id: "points",
    title: "Readings",
    description: "What the control system reads, next to what's really happening.",
    slot: "bench",
    controls: [
      {
        kind: "readout",
        id: "zone",
        point: "VAV-3/ZN-T",
        label: "Room temperature",
        unit: "°F",
        digits: 1,
        value: (o) => o.zoneDisplayed,
        status: zoneStatus,
      },
      {
        kind: "readout",
        id: "flow",
        point: "VAV-3/SA-F",
        label: "Airflow, as the box measures it",
        unit: "cfm",
        value: (o) => o.qBas,
        status: (o) => (o.starved ? "alarm" : "ok"),
        pair: { label: "SP", value: (o) => o.flowSp },
      },
      {
        kind: "readout",
        id: "cmd",
        point: "VAV-3/DPR-CMD",
        label: "Damper command",
        unit: "%",
        value: (o) => o.cmd,
        status: (o) => (o.manual ? "overridden" : "ok"),
        pair: { label: "FB", value: (o) => o.actuatorPct },
      },
      {
        kind: "readout",
        id: "sp",
        point: "SF-1/DSP",
        label: "Duct static pressure at the box",
        unit: "in.",
        digits: 2,
        value: (o) => o.staticIn,
      },
      {
        kind: "readout",
        id: "true-flow",
        point: "airflow",
        label: "Airflow really moving",
        unit: "cfm",
        reality: true,
        value: (o) => o.q,
      },
      {
        kind: "readout",
        id: "signal",
        point: "flow signal",
        label: "Pressure the flow sensor really sees",
        unit: "in.",
        digits: 3,
        reality: true,
        value: (o) => o.vpTrue,
      },
      {
        kind: "readout",
        id: "burned",
        point: "damper",
        label: "Duct pressure the damper burns off",
        unit: "in.",
        digits: 2,
        reality: true,
        value: (o) => o.dpDamper,
      },
    ],
  },
  {
    id: "trend",
    title: "Trend",
    description: "The last 90 seconds of airflow and the room.",
    slot: "bench",
    controls: [
      {
        kind: "trend",
        id: "vav-trend",
        label: "Airflow and room",
        window: 90,
        pens: [
          { id: "zone", label: "Room", unit: "°", axis: "temp", color: "#f3eee4", value: (o) => o.zoneDisplayed },
          { id: "zsp", label: "Setpoint", unit: "°", axis: "temp", color: "#7f7c75", dashed: true, value: (o) => o.zoneSp },
          { id: "flow", label: "Airflow", unit: "%", axis: "pct", color: "#27b7ff", value: (o) => (o.q / o.maxFlow) * 100 },
          { id: "fsp", label: "Wanted", unit: "%", axis: "pct", color: "#27b7ff", dashed: true, value: (o) => (o.flowSp / o.maxFlow) * 100 },
          { id: "dpr", label: "Damper", unit: "%", axis: "pct", color: "#ff5a1f", value: (o) => o.bladePct },
        ],
      },
    ],
  },

  // ── side rack ─────────────────────────────────────────────────────────────────
  {
    id: "box",
    title: "Box",
    description: "Pressure-independent boxes measure their airflow. Older pressure-dependent ones just set the damper where the thermostat says.",
    slot: "side",
    controls: [
      {
        kind: "segmented",
        id: "control",
        label: "Box type",
        options: [
          { value: "independent", label: "Measures airflow" },
          { value: "dependent", label: "Damper only" },
        ],
        get: (i) => i.control,
        set: (i, v) => ({ ...i, control: v as I["control"] }),
      },
    ],
  },
  {
    id: "conditions",
    title: "Duct and room",
    description: "The pressure the fan is pushing through the duct, and the heat the room has to get rid of.",
    slot: "side",
    controls: [
      {
        kind: "slider",
        id: "static",
        label: "Duct pressure at the box",
        unit: "in.",
        min: 0.1,
        max: 3,
        step: 0.05,
        hint: "Static pressure in the supply duct where this box takes its air, in inches of water.",
        get: (i) => i.staticIn,
        set: (i, v) => ({ ...i, staticIn: v }),
      },
      {
        kind: "slider",
        id: "swing",
        label: "Pressure swings ±",
        unit: "in.",
        min: 0,
        max: 0.6,
        step: 0.05,
        hint: "Other boxes on the same duct opening and closing push the pressure here up and down.",
        get: (i) => i.staticSwing,
        set: (i, v) => ({ ...i, staticSwing: v }),
      },
      {
        kind: "slider",
        id: "load",
        label: "Heat in the room",
        unit: "Btu/h",
        min: 0,
        max: 20000,
        step: 250,
        hint: "People, lights, computers and sun. More heat needs more cool air.",
        get: (i) => i.load,
        set: (i, v) => ({ ...i, load: v }),
      },
      {
        kind: "slider",
        id: "sat",
        label: "Supply air temperature",
        unit: "°F",
        min: 50,
        max: 62,
        step: 0.5,
        get: (i) => i.sat,
        set: (i, v) => ({ ...i, sat: v }),
      },
    ],
  },
  {
    id: "setpoints",
    title: "Setpoints",
    description: "The room's target, and the airflow range the box works between.",
    slot: "side",
    controls: [
      {
        kind: "setpoint",
        id: "zone-sp",
        label: "Room cooling setpoint",
        point: "ZN-T-SP",
        unit: "°F",
        min: 68,
        max: 80,
        step: 0.5,
        digits: 1,
        get: (i) => i.zoneSp,
        set: (i, v) => ({ ...i, zoneSp: v }),
      },
      {
        kind: "setpoint",
        id: "min",
        label: "Minimum airflow",
        point: "SA-F-MIN · fresh air",
        unit: "cfm",
        min: 0,
        max: 500,
        step: 10,
        digits: 0,
        get: (i) => i.minFlow,
        set: (i, v) => ({ ...i, minFlow: Math.min(v, i.maxFlow - 50) }),
      },
      {
        kind: "setpoint",
        id: "max",
        label: "Maximum airflow",
        point: "SA-F-MAX",
        unit: "cfm",
        min: 300,
        max: 1200,
        step: 10,
        digits: 0,
        get: (i) => i.maxFlow,
        set: (i, v) => ({ ...i, maxFlow: Math.max(v, i.minFlow + 50) }),
      },
    ],
  },
  {
    id: "control",
    title: "Control",
    description: "Who's driving the damper, and how hard the airflow loop reacts.",
    slot: "side",
    controls: [
      {
        kind: "override",
        id: "override",
        label: "Damper",
        point: "VAV-3/DPR-CMD",
        unit: "%",
        min: 0,
        max: 100,
        step: 1,
        get: (i) => i.override,
        set: (i, v) => ({ ...i, override: v }),
        programValue: (o) => o.loopOut,
        programPriority: 16,
        activePriority: (o) => o.activePriority,
      },
      {
        kind: "knob",
        id: "kp",
        label: "Airflow loop gain",
        unit: "",
        min: 0.2,
        max: 6,
        step: 0.1,
        digits: 1,
        color: "orange",
        warnAbove: 3.5,
        hint: "How hard the damper reacts to airflow error.",
        when: (i: I) => i.control === "independent",
        get: (i) => i.kp,
        set: (i, v) => ({ ...i, kp: v }),
      },
      {
        kind: "knob",
        id: "ti",
        label: "Reset time",
        unit: "s",
        min: 1,
        max: 30,
        step: 1,
        digits: 0,
        color: "white",
        hint: "How patiently the loop works off a steady airflow error.",
        when: (i: I) => i.control === "independent",
        get: (i) => i.ti,
        set: (i, v) => ({ ...i, ti: v }),
      },
    ],
  },
  {
    id: "service",
    title: "Service",
    description: "Break things on purpose.",
    slot: "side",
    controls: [
      {
        kind: "faults",
        id: "faults",
        label: "Fault injector",
        active: (i) => (i.faults.vpOffset !== 0 ? 1 : 0) + (i.faults.kError !== 0 ? 1 : 0) + (i.faults.stuck ? 1 : 0),
        items: [
          {
            kind: "slider",
            id: "drift",
            label: "Flow transducer drift",
            hint: "The pressure sensor's zero has drifted. It adds this to every reading, in inches of water: tiny at full flow, huge at minimum.",
            unit: "in.",
            min: -0.01,
            max: 0.01,
            step: 0.001,
            get: (i) => i.faults.vpOffset,
            set: (i, v) => ({ ...i, faults: { ...i.faults, vpOffset: Math.round(v * 1000) / 1000 } }),
          },
          {
            kind: "slider",
            id: "k",
            label: "Flow sensor reads high by",
            hint: "A dirty flow cross or a wrong K factor in the controller. The box delivers less air than it thinks, at every airflow.",
            unit: "%",
            min: -30,
            max: 30,
            step: 1,
            get: (i) => Math.round(i.faults.kError * 100),
            set: (i, v) => ({ ...i, faults: { ...i.faults, kError: v / 100 } }),
          },
          {
            kind: "toggle",
            id: "stuck",
            label: "Damper linkage slipped",
            hint: "The actuator keeps turning and reporting, but the damper blade stays where it was.",
            capture: "bladePct",
            get: (i) => i.faults.stuck,
            set: (i, on, capture) => ({ ...i, faults: { ...i.faults, stuck: on, stuckAt: on ? Math.round(capture) : i.faults.stuckAt } }),
          },
        ],
      },
    ],
  },
];
