import type { ControlSection } from "@/lab/types";
import { ZONES, type ResetInputs, type ResetOutputs } from "./model";
import { ResetPanel } from "./ResetPanel";

type I = ResetInputs;
type O = ResetOutputs;

const zoneLoad = (k: number) => ({
  kind: "slider" as const,
  id: `load${k + 1}`,
  label: ZONES[k].name,
  unit: "Btu/h",
  min: 0,
  max: 20000,
  step: 250,
  hint: k === 3 ? "The corner office: farthest down the main, with the longest duct run after its box." : undefined,
  get: (i: I) => i.zones[k].load,
  set: (i: I, v: number) => ({ ...i, zones: i.zones.map((z, j) => (j === k ? { ...z, load: v } : z)) }),
});

export const controls: ControlSection<I, O>[] = [
  // ── bench ─────────────────────────────────────────────────────────────────────
  {
    id: "reset",
    title: "Trim & respond",
    description: "The setpoint's steps, each box's damper, and who's asking for more pressure.",
    slot: "bench",
    controls: [
      {
        kind: "custom",
        id: "reset-panel",
        label: "Static pressure reset",
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        Component: ResetPanel as any,
      },
    ],
  },
  {
    id: "points",
    title: "Readings",
    description: "What the control system reads, next to what's really happening.",
    slot: "bench",
    controls: [
      {
        kind: "readout",
        id: "dsp",
        point: "SF-1/DSP",
        label: "Duct static pressure",
        unit: "in.",
        digits: 2,
        value: (o) => o.dsp,
        status: (o) => (o.sensorOffset !== 0 ? "fault" : "ok"),
        pair: { label: "SP", value: (o) => o.sp },
      },
      {
        kind: "readout",
        id: "speed",
        point: "SF-1/SPD",
        label: "Fan speed",
        unit: "Hz",
        digits: 1,
        value: (o) => o.fanHz,
        status: (o) => (o.manual ? "overridden" : "ok"),
        pair: { label: "CMD", value: (o) => (o.fanCmd / 100) * 60 },
      },
      {
        kind: "readout",
        id: "kw",
        point: "SF-1/KW",
        label: "Fan power",
        unit: "kW",
        digits: 2,
        value: (o) => o.kw,
      },
      {
        kind: "readout",
        id: "flow",
        point: "AHU-1/SA-F",
        label: "Supply airflow",
        unit: "cfm",
        value: (o) => o.total,
      },
      {
        kind: "readout",
        id: "requests",
        point: "AHU-1/SP-REQ",
        label: "Requests counted",
        unit: "",
        value: (o) => o.requests,
      },
      {
        kind: "readout",
        id: "fixed-kw",
        point: "fixed setpoint",
        label: "Fan power at a fixed setpoint",
        unit: "kW",
        digits: 2,
        reality: true,
        value: (o) => o.kwFixed,
      },
      {
        kind: "readout",
        id: "burned",
        point: "dampers",
        label: "Dampers burn off (average)",
        unit: "in.",
        digits: 2,
        reality: true,
        value: (o) => o.burned,
      },
      {
        kind: "readout",
        id: "true-dsp",
        point: "duct static",
        label: "Duct static, really",
        unit: "in.",
        digits: 2,
        reality: true,
        value: (o) => o.dspTrue,
      },
    ],
  },
  {
    id: "trend",
    title: "Trend",
    description: "The last 3 minutes of the setpoint, the static, the fan and the most-open damper.",
    slot: "bench",
    controls: [
      {
        kind: "trend",
        id: "reset-trend",
        label: "Static and fan",
        window: 180,
        left: { tick: "", step: 0.25, minSpan: 0.5, digits: 2, floor: 0 },
        pens: [
          { id: "static", label: "Static", unit: " in.", axis: "temp", color: "#f3eee4", value: (o) => o.dsp },
          { id: "sp", label: "Setpoint", unit: " in.", axis: "temp", color: "#7f7c75", dashed: true, value: (o) => o.sp },
          { id: "fan", label: "Fan", unit: "%", axis: "pct", color: "#27b7ff", value: (o) => o.fanPct },
          { id: "dmp", label: "Most-open damper", unit: "%", axis: "pct", color: "#ff5a1f", value: (o) => o.mostOpen },
        ],
      },
    ],
  },

  // ── side rack ─────────────────────────────────────────────────────────────────
  {
    id: "setpoint",
    title: "Static pressure setpoint",
    description: "Hold one number all day, or let the boxes' requests move it.",
    slot: "side",
    controls: [
      {
        kind: "segmented",
        id: "mode",
        label: "Setpoint",
        options: [
          { value: "fixed", label: "Fixed" },
          { value: "reset", label: "Trim & respond" },
        ],
        get: (i) => i.mode,
        set: (i, v) => ({ ...i, mode: v as I["mode"] }),
      },
      {
        kind: "slider",
        id: "spmax",
        label: "Fixed setpoint, and the most the reset can ask for",
        unit: "in.",
        min: 0.5,
        max: 2.5,
        step: 0.05,
        hint: "What the designer picked for the hottest afternoon. Trim & respond never goes above it.",
        get: (i) => i.spMax,
        set: (i, v) => ({ ...i, spMax: v }),
      },
      {
        kind: "knob",
        id: "ignores",
        label: "Ignored requests (I)",
        unit: "",
        min: 0,
        max: 4,
        step: 1,
        digits: 0,
        color: "white",
        warnAbove: 1,
        hint: "Requests let go by before responding. Guideline 36's example is 2, for a floor with dozens of boxes.",
        when: (i: I) => i.mode === "reset",
        get: (i) => i.ignores,
        set: (i, v) => ({ ...i, ignores: Math.round(v) }),
      },
      {
        kind: "knob",
        id: "trim",
        label: "Trim per step",
        unit: "in.",
        min: 0.01,
        max: 0.15,
        step: 0.01,
        digits: 2,
        color: "blue",
        hint: "How far the setpoint drops each step nobody (counted) is asking.",
        when: (i: I) => i.mode === "reset",
        get: (i) => i.trim,
        set: (i, v) => ({ ...i, trim: v }),
      },
      {
        kind: "knob",
        id: "respond",
        label: "Respond per request",
        unit: "in.",
        min: 0.02,
        max: 0.3,
        step: 0.01,
        digits: 2,
        color: "orange",
        warnAbove: 0.15,
        hint: "How far the setpoint rises for each request over the ignored ones, up to 0.13 in. a step.",
        when: (i: I) => i.mode === "reset",
        get: (i) => i.respond,
        set: (i, v) => ({ ...i, respond: v, respondMax: Math.max(i.respondMax, v) }),
      },
    ],
  },
  {
    id: "zones",
    title: "Heat in each zone",
    description: "People, lights, computers and sun. More heat needs more cool air, and more air needs more pressure.",
    slot: "side",
    controls: [zoneLoad(0), zoneLoad(1), zoneLoad(2), zoneLoad(3)],
  },
  {
    id: "fan",
    title: "Supply fan",
    description: "The fan loop sets the drive's speed to hold the duct static at the setpoint.",
    slot: "side",
    controls: [
      {
        kind: "override",
        id: "override",
        label: "Fan speed",
        point: "SF-1/SPD-CMD",
        unit: "%",
        min: 0,
        max: 100,
        step: 1,
        get: (i) => i.override,
        set: (i, v) => ({ ...i, override: v }),
        programValue: (o) => o.fanLoop,
        programPriority: 16,
        activePriority: (o) => o.activePriority,
      },
    ],
  },
  {
    id: "service",
    title: "Service",
    description: "Break things on purpose.",
    slot: "side",
    controls: [
      {
        kind: "faults",
        id: "faults",
        label: "Fault injector",
        active: (i) => (i.faults.slipped ? 1 : 0) + (i.faults.crushed ? 1 : 0) + (i.faults.sensorOffset !== 0 ? 1 : 0),
        items: [
          {
            kind: "toggle",
            id: "slipped",
            label: "Offices damper linkage slipped",
            hint: "The actuator turns and reports, but the blade stays at 25 %. The box can never get its air, so it asks for more pressure forever.",
            get: (i) => i.faults.slipped,
            set: (i, on) => ({ ...i, faults: { ...i.faults, slipped: on } }),
          },
          {
            kind: "toggle",
            id: "crushed",
            label: "Corner office flex crushed",
            hint: "Someone stepped on the flex duct above the ceiling. The box needs more pressure to push the same air through it.",
            get: (i) => i.faults.crushed,
            set: (i, on) => ({ ...i, faults: { ...i.faults, crushed: on } }),
          },
          {
            kind: "slider",
            id: "offset",
            label: "Static sensor reads off by",
            hint: "A cracked tube or a drifted transducer. The fan holds the reading at the setpoint, so the duct really runs this much the other way.",
            unit: "in.",
            min: -0.3,
            max: 0.3,
            step: 0.01,
            get: (i) => i.faults.sensorOffset,
            set: (i, v) => ({ ...i, faults: { ...i.faults, sensorOffset: Math.round(v * 100) / 100 } }),
          },
        ],
      },
    ],
  },
];
